# -*- coding: utf-8 -*-
"""Copy of MVP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-K2cB4s5hpRm9Gx5Roj1wVKc-byHeHqZ

# Minimum Viable Product (MVP)

## Setup

### Installation
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf datara_transfer/
!rm -rf sam2/
!rm -rf PartPacker/

# Commented out IPython magic to ensure Python compatibility.
# datara_transfer
# %cd /content
!git clone https://github.com/rishrav/datara_transfer

# Commented out IPython magic to ensure Python compatibility.
#datara transfer aayush version
# %cd /content
!git clone https://github.com/AayushDubey50/datara_ai

# Qwen VLM Model
!pip install qwen-vl-utils[decord]==0.0.8

# Commented out IPython magic to ensure Python compatibility.
# VSAM
# %cd /content
!git clone https://github.com/facebookresearch/sam2.git
# %cd sam2
!pip install -e .
# !pip install tqdm hydra-core iopath
# %cd /content

# # Grounded SAM2
# %cd /content
# !git clone https://github.com/IDEA-Research/Grounded-SAM-2.git

# %cd checkpoints
# !bash download_ckpts.sh

# %cd ../gdino_checkpoints
# !bash download_ckpts.sh

# Commented out IPython magic to ensure Python compatibility.
# PartPacker
# %cd /content
!git clone https://github.com/NVlabs/PartPacker.git

"""### Dependencies"""

!pip install transformers==4.41.0 accelerate

# VSAM
!pip install matplotlib
!pip install 'git+https://github.com/facebookresearch/sam2.git'

!mkdir -p /content/checkpoints/
!wget -P /content/checkpoints/ https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_large.pt

# !pip install torchaudio

# PartPacker

# Core stability
!pip install --no-deps "numpy==1.26.4" "scipy<1.14" "opencv-python-headless==4.9.0.80"

# Deep learning
!pip install --no-deps torch torchvision tqdm einops transformers

# ONNX + protobuf
!pip install --no-deps onnxruntime "protobuf==4.25.3"

# Mesh & geometry
#!pip install --no-deps "trimesh==4.4.9" "pymeshlab==2022.2.post4" fpsample

!pip install pybind11
!pip install pymeshlab==2025.7 trimesh==4.4.9 fpsample
!pip install --no-deps "pymcubes==0.1.2"  # (import as mcubes)

# Pre/Post-processing
!pip install --no-deps "rembg==2.0.67" "pymatting==1.1.12"

# NVLabs utilities & missing helpers
!pip install --no-deps "kiui==0.2.18" "meshiki==0.0.7"
!pip install --no-deps "varname==0.15.0" "objprint==0.3.0" "lazy-loader==0.4" "executing==2.2.1" "typing_extensions==4.12.2"

# Flexible Collision Library
!pip install python-fcl



# !python - <<'PY'
mods = ["torch", "torchvision", "numpy", "trimesh", "fpsample", "einops", "onnxruntime", "rembg", "kiui", "mcubes",
        "tqdm", "cv2", "pymeshlab", "transformers", "pymatting", "meshiki", "google.protobuf", "varname", "objprint",
        "lazy_loader", "executing", "fcl"]
missing=[]
for m in mods:
    try: __import__(m.replace("-","_"))
    except Exception as e: missing.append((m,str(e)))
print("Missing:", [m for m,_ in missing] or "None")

"""### Imports"""

# --- Qwen2.5-VL Setup for Google Colab ---
!pip install -qU transformers accelerate bitsandbytes qwen-vl-utils
!pip install -qU git+https://github.com/huggingface/transformers.git

# Restart runtime so the new transformers version loads
import os
os._exit(0)

# VLM
import torch
from PIL import Image
from transformers import AutoProcessor, AutoModelForCausalLM
from transformers.image_utils import load_image
from transformers.video_utils import load_video

from transformers import Qwen2_5_VLForConditionalGeneration, AutoTokenizer # AutoProcessor
from qwen_vl_utils import process_vision_info

def generate_text(model, processor, filepath, label, detail):
    # Get media type, image/video
    if filepath.endswith(".jpg") or filepath.endswith(".jpeg") or filepath.endswith(".png"):
        media_type = "image"
        # Blip2 processor handles image loading internally, so load the raw image with PIL
        raw_image = Image.open(filepath).convert('RGB')
    # elif filepath.endswith(".mp4") or filepath.endswith(".mov"):
    #     media_type = "video"
    #     # The Qwen model seems to handle video loading internally through process_vision_info
    #     # Blip2 does not have native video support in this function
    #     raise ValueError("Blip2 model does not support video input in this function.")
    else:
        raise ValueError("Unsupported media type or Blip2 does not support video input.")

    # Load prompt based off of the kind of detail requested
    if detail == "condition":
        prompt = "What are the qualities of this welding job?"
    elif detail == "operation type":
        prompt = "What is the operation type of the welding job?"
    elif detail == "sensor modalities":
        prompt = "What are the sensor modalities used in this welding job?"
    else:
        raise ValueError("Unsupported detail type")


    # Prepare the input for Blip2
    inputs = processor(raw_image, text=prompt, return_tensors="pt").to(model.device, torch.float16)

    # Inference: Generation of the output
    generated_ids = model.generate(**inputs, max_new_tokens=128)
    output_text = processor.batch_decode(
        generated_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )
    return output_text

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/sam2

# VSAM
import cv2
from google.colab.patches import cv2_imshow

import torch
import torchvision

import os
# if using Apple MPS, fall back to CPU for unsupported ops
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
import numpy as np
# import torch
import matplotlib.pyplot as plt
# from PIL import Image

from sam2.build_sam import build_sam2
from sam2.build_sam import build_sam2_video_predictor
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
from sam2.sam2_image_predictor import SAM2ImagePredictor

# PartPacker
import sys

if '/content/PartPacker' not in sys.path:
    sys.path.append('/content/PartPacker')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PartPacker

import glob
# import os
import argparse
from datetime import datetime

import cv2
import gradio as gr
import kiui
# import numpy as np
import rembg
# import torch
import torch.nn as nn
import trimesh

# Memory optimization setting
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

# try:
#     # running on Hugging Face Spaces
#     import spaces

# except ImportError:
#     # running locally, use a dummy space
#     class spaces:
#         class GPU:
#             def __init__(self, duration=60):
#                 self.duration = duration

#             def __call__(self, func):
#                 return func

class spaces:
    class GPU:
        def __init__(self, duration=60):
            self.duration = duration

        def __call__(self, func):
            return func


# # download checkpoints
# from huggingface_hub import hf_hub_download

from flow.configs.schema import ModelConfig
from flow.model import Model
from flow.utils import get_random_color, recenter_foreground
from vae.utils import postprocess_mesh

"""### Helpers + Variables"""

# VLM

# default: Load the model on the available device(s)
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2.5-VL-3B-Instruct", torch_dtype="auto", device_map="auto"
)

# We recommend enabling flash_attention_2 for better acceleration and memory saving, especially in multi-image and video scenarios.
# model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
#     "Qwen/Qwen2.5-VL-3B-Instruct",
#     torch_dtype=torch.bfloat16,
#     attn_implementation="flash_attention_2",
#     device_map="auto",
# )

# default processer
processor = AutoProcessor.from_pretrained("Qwen/Qwen2.5-VL-3B-Instruct")

# The default range for the number of visual tokens per image in the model is 4-16384.
# You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2.5-VL-3B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/sam2

# VSAM
using_colab = True

# select the device for computation
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
print(f"using device: {device}")

if device.type == "cuda":
    # use bfloat16 for the entire notebook
    torch.autocast("cuda", dtype=torch.bfloat16).__enter__()
    # turn on tfloat32 for Ampere GPUs (https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices)
    if torch.cuda.get_device_properties(0).major >= 8:
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
elif device.type == "mps":
    print(
        "\nSupport for MPS devices is preliminary. SAM 2 is trained with CUDA and might "
        "give numerically different outputs and sometimes degraded performance on MPS. "
        "See e.g. https://github.com/pytorch/pytorch/issues/84936 for a discussion."
    )


np.random.seed(3)

def show_anns(anns, borders=True):
    if len(anns) == 0:
        return
    sorted_anns = sorted(anns, key=(lambda x: x['area']), reverse=True)
    ax = plt.gca()
    ax.set_autoscale_on(False)

    img = np.ones((sorted_anns[0]['segmentation'].shape[0], sorted_anns[0]['segmentation'].shape[1], 4))
    img[:, :, 3] = 0
    for ann in sorted_anns:
        m = ann['segmentation']
        color_mask = np.concatenate([np.random.random(3), [0.5]])
        img[m] = color_mask
        if borders:
            import cv2
            contours, _ = cv2.findContours(m.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
            # Try to smooth contours
            contours = [cv2.approxPolyDP(contour, epsilon=0.01, closed=True) for contour in contours]
            cv2.drawContours(img, contours, -1, (0, 0, 1, 0.4), thickness=1)

    ax.imshow(img)


def image_show_mask(mask, ax, random_color=False, borders = True):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.6])], axis=0)
    else:
        color = np.array([30/255, 144/255, 255/255, 0.6])
    h, w = mask.shape[-2:]
    mask = mask.astype(np.uint8)
    mask_image =  mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    if borders:
        import cv2
        contours, _ = cv2.findContours(mask,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        # Try to smooth contours
        contours = [cv2.approxPolyDP(contour, epsilon=0.01, closed=True) for contour in contours]
        mask_image = cv2.drawContours(mask_image, contours, -1, (1, 1, 1, 0.5), thickness=2)
    ax.imshow(mask_image)

def image_show_points(coords, labels, ax, marker_size=375):
    pos_points = coords[labels==1]
    neg_points = coords[labels==0]
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)

def image_show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0, 0, 0, 0), lw=2))

def image_show_masks(image, masks, scores, point_coords=None, box_coords=None, input_labels=None, borders=True):
    for i, (mask, score) in enumerate(zip(masks, scores)):
        plt.figure(figsize=(10, 10))
        plt.imshow(image)
        show_mask(mask, plt.gca(), borders=borders)
        if point_coords is not None:
            assert input_labels is not None
            show_points(point_coords, input_labels, plt.gca())
        if box_coords is not None:
            # boxes
            show_box(box_coords, plt.gca())
        if len(scores) > 1:
            plt.title(f"Mask {i+1}, Score: {score:.3f}", fontsize=18)
        plt.axis('off')
        plt.show()


def video_show_mask(mask, ax, obj_id=None, random_color=False):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.6])], axis=0)
    else:
        cmap = plt.get_cmap("tab10")
        cmap_idx = 0 if obj_id is None else obj_id
        color = np.array([*cmap(cmap_idx)[:3], 0.6])
    h, w = mask.shape[-2:]
    mask_image = mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    ax.imshow(mask_image)

def video_show_points(coords, labels, ax, marker_size=200):
    pos_points = coords[labels==1]
    neg_points = coords[labels==0]
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)

def video_show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0, 0, 0, 0), lw=2))


sam2_checkpoint = "../checkpoints/sam2.1_hiera_large.pt"
model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml"

sam2 = build_sam2(model_cfg, sam2_checkpoint, device=device, apply_postprocessing=False)

mask_generator = SAM2AutomaticMaskGenerator(sam2)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PartPacker
!mkdir -p pretrained
# %cd pretrained
!wget -q https://huggingface.co/nvidia/PartPacker/resolve/main/flow.pt
!wget -q https://huggingface.co/nvidia/PartPacker/resolve/main/vae.pt
# %cd /content

import gc, torch; gc.collect(); torch.cuda.empty_cache()
print("CUDA available:", torch.cuda.is_available())

flow_ckpt_path = "/content/PartPacker/pretrained/flow.pt"
vae_ckpt_path = "/content/PartPacker/pretrained/vae.pt"

TRIMESH_GLB_EXPORT = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]]).astype(np.float32)
MAX_SEED = np.iinfo(np.int32).max
bg_remover = rembg.new_session()

# model config
model_config = ModelConfig(
    vae_conf="vae.configs.part_woenc",
    vae_ckpt_path=vae_ckpt_path,
    qknorm=True,
    qknorm_type="RMSNorm",
    use_pos_embed=False,
    dino_model="dinov2_vitl14_reg", # Set to the supported name
    hidden_dim=1024, # Set to the required dimension for dinov2_vitl14_reg
    flow_shift=3.0,
    logitnorm_mean=1.0,
    logitnorm_std=1.0,
    latent_size=4096,
    use_parts=True,
)

gpu_config = {'num_gpus': 1 if torch.cuda.is_available() else 0}
model = Model(model_config).eval().cuda().bfloat16()
multi_gpu_enabled = False

# load weight
ckpt_dict = torch.load(flow_ckpt_path, weights_only=True)
if multi_gpu_enabled:
    model.base_model.load_state_dict(ckpt_dict, strict=True)
else:
    model.load_state_dict(ckpt_dict, strict=True)

# get random seed
def get_random_seed(randomize_seed, seed):
    if randomize_seed:
        seed = np.random.randint(0, MAX_SEED)
    return seed

"""## VLM Model

### Cloning repo + installing dependencies
"""

!pip install git+https://github.com/huggingface/transformers accelerate

!pip install qwen-vl-utils[decord]==0.0.8

import torch
from PIL import Image
from transformers import AutoProcessor, AutoModelForCausalLM
from transformers.image_utils import load_image

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Load images
image1 = load_image("/content/datara_ai/backend/dataset_list/BMW_Front_Bumper/egos/BMW_Front_Bumper_1_ego_base.jpg")

import cv2
from google.colab.patches import cv2_imshow

cv2_imshow(cv2.imread("/content/datara_ai/backend/dataset_list/BMW_Front_Bumper/egos/BMW_Front_Bumper_1_ego_base.jpg", cv2.IMREAD_UNCHANGED))

"""### Load Qwen VLM Model"""

from transformers import Qwen2_5_VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2.5-VL-3B-Instruct", torch_dtype="auto", device_map="auto"
)

# We recommend enabling flash_attention_2 for better acceleration and memory saving, especially in multi-image and video scenarios.
# model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
#     "Qwen/Qwen2.5-VL-3B-Instruct",
#     torch_dtype=torch.bfloat16,
#     attn_implementation="flash_attention_2",
#     device_map="auto",
# )

# default processer
processor = AutoProcessor.from_pretrained("Qwen/Qwen2.5-VL-3B-Instruct")

# The default range for the number of visual tokens per image in the model is 4-16384.
# You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2.5-VL-3B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

"""### Generate Text Function"""

# from qwen_vl_utils import load_image, load_video
from transformers.image_utils import load_image
from transformers.video_utils import load_video
from qwen_vl_utils import process_vision_info

def generate_text(model, processor, filepath, label, detail):
    # Get media type, image/video
    if filepath.endswith(".jpg") or filepath.endswith(".jpeg") or filepath.endswith(".png"):
        media_type = "image"
        media = load_image(filepath)
    elif filepath.endswith(".mp4") or filepath.endswith(".mov"):
        media_type = "video"
        media = load_video(filepath)
    else:
        raise ValueError("Unsupported media type")

    # Load prompt based off of the kind of detail requested
    prompt = "This is a " + ("successful" if label == "good" else "defective") + "welding job. "
    if detail == "condition":
        prompt += "What 1-2 word qualities satisfy this condition?"
    elif detail == "operation type":
        prompt += "What is its operation type?"
    elif detail == "sensor modalities":
        prompt += "What are the sensor modalities?"
    else:
        raise ValueError("Unsupported detail type")

    # Prepare the input
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": media_type,
                    media_type: media,
                },
                {
                    "type": "text",
                    "text": prompt
                },
            ],
        }
    ]

    # Preparation for inference
    text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )
    inputs = inputs.to("cuda")

    # Inference: Generation of the output
    generated_ids = model.generate(**inputs, max_new_tokens=128)
    generated_ids_trimmed = [
        out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]
    output_text = processor.batch_decode(
        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )
    return [o for output in output_text for o in output.split("\\n")]

"""#### Condition"""

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": image1,
            },
            {
                "type": "text",
                "text": "Give me a list of one word qualities about this image that makes it a successful welding job."
            },
        ],
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
# print(output_text)
for output in output_text:
    for o in output.split("\\n"):
        print(o)

"""#### Operation Type"""

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": image1,
            },
            {
                "type": "text",
                "text": "What is the operation type of the welding job in this image?"
            },
        ],
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
# print(output_text)
for output in output_text:
    for o in output.split("\\n"):
        print(o)

"""#### Sensor Modalities"""

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": image1,
            },
            {
                "type": "text",
                "text": "Detect the sensor modalities of the welding job in the image."
            },
        ],
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
# print(output_text)
for output in output_text:
    for o in output.split("\\n"):
        print(o)

"""# Testing VLM for BMW images"""

"/content/datara_ai/backend/dataset_list/BMW_Front_Bumper/egos/BMW_Front_Bumper_1_ego_base.jpg"

from transformers.image_utils import load_image
from transformers.video_utils import load_video
from qwen_vl_utils import process_vision_info

def generate_bmw_annotation(model, processor, filepath, detail):
    """
    Generate annotations for BMW egocentric vehicle images using a Vision-Language Model.
    """

    # Detect media type
    filepath_lower = filepath.lower()
    if filepath_lower.endswith((".jpg", ".jpeg", ".png")):
        media_type = "image"
        media = load_image(filepath)
    elif filepath_lower.endswith((".mp4", ".mov")):
        media_type = "video"
        media = load_video(filepath)
    else:
        raise ValueError(f"Unsupported media type for file: {filepath}")

    # Prompt templates for annotation types
    if detail == "viewpoint":
        prompt = (
            "You are an automotive vision model. Describe the camera viewpoint of this "
            "egocentric image of a BMW vehicle. Include the viewing angle (frontal, low-angle, "
            "high-angle, oblique), distance from the grille, symmetry, and any perspective distortion."
        )

    elif detail == "grille_features":
        prompt = (
            "Analyze the BMW kidney grille in the image. Describe its shape, vertical bar count, "
            "bar spacing, chrome/metallic finish, symmetry, and alignment with the hood, headlights, "
            "and bumper. Identify any visible irregularities or defects."
        )

    elif detail == "component_identification":
        prompt = (
            "Identify all major exterior vehicle components visible in this egocentric view. "
            "List parts such as grille, headlights, bumper vents, sensors, hood, air intakes, and "
            "other assemblies. Provide brief descriptions of their visual appearance."
        )

    elif detail == "alignment_quality":
        prompt = (
            "Evaluate the alignment and fit quality of the visible exterior components. "
            "Comment on hood-to-grille alignment, panel gaps, bumper alignment, and symmetry. "
            "List any QC concerns you can visually detect."
        )

    elif detail == "factory_context":
        prompt = (
            "Describe the factory or assembly-line environment around the vehicle. Identify equipment, "
            "tools, conveyor systems, lighting, or robotic machinery visible in the background."
        )

    elif detail == "damage_or_defects":
        prompt = (
            "Inspect the BMW vehicle components for any damage, scratches, dents, misalignment, "
            "missing parts, or manufacturing irregularities. Provide a concise list of issues. "
            "If none are visible, state that clearly."
        )

    else:
        raise ValueError(f"Unsupported detail type: {detail}")

    # Prepare messages for VLM
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": media_type,
                    media_type: media,
                },
                {
                    "type": "text",
                    "text": prompt,
                },
            ],
        }
    ]

    # Convert to model-friendly format
    text_prompt = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    image_inputs, video_inputs = process_vision_info(messages)

    inputs = processor(
        text=[text_prompt],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt"
    ).to("cuda")

    # Generate model output
    generated_ids = model.generate(**inputs, max_new_tokens=200)

    # Remove input tokens from output
    trimmed_ids = [
        out[len(inp):]
        for inp, out in zip(inputs.input_ids, generated_ids)
    ]

    # Decode output
    output_text = processor.batch_decode(
        trimmed_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False
    )

    # Split into lines for convenience
    final_output = []
    for o in output_text:
        final_output.extend(o.split("\n"))

    return final_output

# Example: Load your model + processor (your code may differ)
# from transformers import AutoModelForCausalLM, AutoProcessor
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto")
# processor = AutoProcessor.from_pretrained("Qwen/Qwen-VL-Chat")

filepath = "/content/datara_ai/backend/dataset_list/BMW_Front_Bumper/egos/BMW_Front_Bumper_1_ego_base.jpg"

# Try different annotation types
outputs = generate_bmw_annotation(
    model=model,
    processor=processor,
    filepath=filepath,
    detail="grille_features"
)

print("\n===== BMW Grille Features Annotation =====\n")
for line in outputs:
    print(line)

def annotate_bmw_image_all(model, processor, filepath):
    """
    Runs all BMW annotation categories on a single image and returns
    a dictionary with the annotation results for each component.
    """

    detail_types = [
        "viewpoint",
        "grille_features",
        "component_identification",
        "alignment_quality",
        "factory_context",
        "damage_or_defects"
    ]

    results = {}

    for detail in detail_types:
        try:
            output = generate_bmw_annotation(
                model=model,
                processor=processor,
                filepath=filepath,
                detail=detail
            )
            results[detail] = output
        except Exception as e:
            results[detail] = [f"Error: {e}"]

    return results

filepath = "/content/datara_ai/backend/dataset_list/BMW_Front_Bumper/egos/BMW_Front_Bumper_1_ego_base.jpg"

all_annotations = annotate_bmw_image_all(
    model=model,
    processor=processor,
    filepath=filepath
)

print("\n=============== BMW Egocentric Image Annotations ===============\n")

for key, value in all_annotations.items():
    print(f"\n--- {key.upper()} ---\n")
    for line in value:
        print(line)



"""## Visual segmentation model: Segment Anything Model 2 (SAM 2)

### Installation
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/
!git clone https://github.com/facebookresearch/sam2.git
# %cd sam2
!pip install -e .

"""### Input image"""

import cv2
from google.colab.patches import cv2_imshow

image_path = '/content/datara_transfer/backend/dataset/train/images/good/good_001.jpg'

image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
# Resize just to occupy less space in NB cell
cv2_imshow(cv2.resize(image, (518, 518)))

"""### Image mask"""

using_colab = True

if using_colab:
    import torch
    import torchvision
    print("PyTorch version:", torch.__version__)
    print("Torchvision version:", torchvision.__version__)
    print("CUDA is available:", torch.cuda.is_available())
    import sys
    !{sys.executable} -m pip install opencv-python matplotlib
    !{sys.executable} -m pip install 'git+https://github.com/facebookresearch/sam2.git'

    !mkdir -p images
    # !wget -P images https://raw.githubusercontent.com/facebookresearch/sam2/main/notebooks/images/truck.jpg
    # !wget -P images https://raw.githubusercontent.com/facebookresearch/sam2/main/notebooks/images/groceries.jpg

    !mkdir -p ../checkpoints/
    !wget -P ../checkpoints/ https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_large.pt

# select the device for computation
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
print(f"using device: {device}")

if device.type == "cuda":
    # use bfloat16 for the entire notebook
    torch.autocast("cuda", dtype=torch.bfloat16).__enter__()
    # turn on tfloat32 for Ampere GPUs (https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices)
    if torch.cuda.get_device_properties(0).major >= 8:
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
elif device.type == "mps":
    print(
        "\nSupport for MPS devices is preliminary. SAM 2 is trained with CUDA and might "
        "give numerically different outputs and sometimes degraded performance on MPS. "
        "See e.g. https://github.com/pytorch/pytorch/issues/84936 for a discussion."
    )

import numpy as np

input_point = np.array([[259, 375]])
input_label = np.array([1])

import torch
from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor

sam2_checkpoint = "../checkpoints/sam2.1_hiera_large.pt"
model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml"

sam2_model = build_sam2(model_cfg, sam2_checkpoint, device=device)

predictor = SAM2ImagePredictor(sam2_model)

with torch.inference_mode(), torch.autocast("cuda", dtype=torch.bfloat16):
    predictor.set_image(image)
    masks, scores, logits = predictor.predict(
        # point_coords=input_point,
        # point_labels=input_label,
        # box=None,
        # multimask_output=True,
    )

import os
# if using Apple MPS, fall back to CPU for unsupported ops
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
import numpy as np
import torch
import matplotlib.pyplot as plt
from PIL import Image

def show_mask(mask, ax, random_color=False, borders = True):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.6])], axis=0)
    else:
        color = np.array([30/255, 144/255, 255/255, 0.6])
    h, w = mask.shape[-2:]
    mask = mask.astype(np.uint8)
    mask_image =  mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    if borders:
        import cv2
        contours, _ = cv2.findContours(mask,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        # Try to smooth contours
        contours = [cv2.approxPolyDP(contour, epsilon=0.01, closed=True) for contour in contours]
        mask_image = cv2.drawContours(mask_image, contours, -1, (1, 1, 1, 0.5), thickness=2)
    ax.imshow(mask_image)

def show_points(coords, labels, ax, marker_size=375):
    pos_points = coords[labels==1]
    neg_points = coords[labels==0]
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)

def show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0, 0, 0, 0), lw=2))

def show_masks(image, masks, scores, point_coords=None, box_coords=None, input_labels=None, borders=True):
    for i, (mask, score) in enumerate(zip(masks, scores)):
        plt.figure(figsize=(10, 10))
        plt.imshow(image)
        show_mask(mask, plt.gca(), borders=borders)
        if point_coords is not None:
            assert input_labels is not None
            show_points(point_coords, input_labels, plt.gca())
        if box_coords is not None:
            # boxes
            show_box(box_coords, plt.gca())
        if len(scores) > 1:
            plt.title(f"Mask {i+1}, Score: {score:.3f}", fontsize=18)
        plt.axis('off')
        plt.show()

sorted_ind = np.argsort(scores)[::-1]
masks = masks[sorted_ind]
scores = scores[sorted_ind]
logits = logits[sorted_ind]

# show_masks(image, masks, scores, point_coords=input_point, input_labels=input_label, borders=True)
show_masks(image, masks, scores)

mask = masks[0]
mask.shape

mask[:, :, np.newaxis].shape

cv2.imread(image_path, cv2.IMREAD_UNCHANGED).shape

image.shape

cv2.split(cv2.imread('/content/PartPacker/assets/images/barrel.png', cv2.IMREAD_UNCHANGED))[3].dtype

b,g,r = cv2.split(cv2.imread('/content/PartPacker/assets/images/barrel.png', cv2.IMREAD_UNCHANGED))[:3]

b,g,r = cv2.split(image)[:3]

(b.shape,g.shape,r.shape,mask.shape)

mask[0][0]

cv2.merge((b, g, r, mask.astype(np.uint8))).shape

print((cv2.imread('/content/PartPacker/assets/images/barrel.png', cv2.IMREAD_UNCHANGED)).shape)

print(((cv2.imread('/content/PartPacker/assets/images/barrel.png', cv2.IMREAD_UNCHANGED))[:,:,:3]).shape)

print(((image)[:,:,:3]).shape)

(image.shape, mask.shape, mask[:,:,np.newaxis].shape)

masked_image = image * mask[:, :, np.newaxis]
# masked_image = cv2.merge((b, g, r, mask.astype(np.uint8)))
plt.figure(figsize=(10, 10))
plt.imshow(masked_image)
plt.axis('off')

masked_image.shape

b,g,r = cv2.split(masked_image)
cv2.merge((b,g,r,np.ones(b.shape, dtype=b.dtype))).shape

cv2_imshow(masked_image)

masked_image = cv2.merge((b,g,r,np.ones(b.shape, dtype=b.dtype)*255))
cv2_imshow(masked_image)

masked_image.shape

!mkdir -p /content/output/masks

# JPG files don't have alpha channels, use PNG as done below

cv2.imwrite('/content/output/masks/good_001.png', masked_image)

cv2.imread('/content/output/masks/good_001.png', cv2.IMREAD_UNCHANGED).shape

"""## 2D to 3D replication using PartPacker

### Clone repo
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf PartPacker
!git clone https://github.com/NVlabs/PartPacker.git
# %cd PartPacker

"""### Dependencies"""

# Core stability
!pip install --no-deps "numpy==1.26.4" "scipy<1.14" "opencv-python-headless==4.9.0.80"

# Deep learning
!pip install --no-deps torch torchvision tqdm einops transformers

# ONNX + protobuf
!pip install --no-deps onnxruntime "protobuf==4.25.3"

# Mesh & geometry
#!pip install --no-deps "trimesh==4.4.9" "pymeshlab==2022.2.post4" fpsample

!pip install pybind11
!pip install pymeshlab==2025.7 trimesh==4.4.9 fpsample
!pip install --no-deps "pymcubes==0.1.2"  # (import as mcubes)

# Pre/Post-processing
!pip install --no-deps "rembg==2.0.67" "pymatting==1.1.12"

# NVLabs utilities & missing helpers
!pip install --no-deps "kiui==0.2.18" "meshiki==0.0.7"
!pip install --no-deps "varname==0.15.0" "objprint==0.3.0" "lazy-loader==0.4" "executing==2.2.1" "typing_extensions==4.12.2"

# Flexible Collision Library
!pip install python-fcl

"""### Model weights"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PartPacker
!mkdir -p pretrained
# %cd pretrained
!wget -q https://huggingface.co/nvidia/PartPacker/resolve/main/flow.pt
!wget -q https://huggingface.co/nvidia/PartPacker/resolve/main/vae.pt
# %cd /content/PartPacker

"""### Verify Installation"""

# !python - <<'PY'
mods = ["torch", "torchvision", "numpy", "trimesh", "fpsample", "einops", "onnxruntime", "rembg", "kiui", "mcubes",
        "tqdm", "cv2", "pymeshlab", "transformers", "pymatting", "meshiki", "google.protobuf", "varname", "objprint",
        "lazy_loader", "executing", "fcl"]
missing=[]
for m in mods:
    try: __import__(m.replace("-","_"))
    except Exception as e: missing.append((m,str(e)))
print("Missing:", [m for m,_ in missing] or "None")

import gc, torch; gc.collect(); torch.cuda.empty_cache()
print("CUDA available:", torch.cuda.is_available())

"""### Imports + Helpers + Variables"""

import sys

if '/content/PartPacker' not in sys.path:
    sys.path.append('/content/PartPacker')

import glob
import os
import argparse
from datetime import datetime

import cv2
import gradio as gr
import kiui
import numpy as np
import rembg
import torch
import torch.nn as nn
import trimesh

# Memory optimization setting
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

try:
    # running on Hugging Face Spaces
    import spaces

except ImportError:
    # running locally, use a dummy space
    class spaces:
        class GPU:
            def __init__(self, duration=60):
                self.duration = duration

            def __call__(self, func):
                return func


# # download checkpoints
# from huggingface_hub import hf_hub_download

from flow.configs.schema import ModelConfig
from flow.model import Model
from flow.utils import get_random_color, recenter_foreground
from vae.utils import postprocess_mesh

from google.colab.patches import cv2_imshow

flow_ckpt_path = "/content/PartPacker/pretrained/flow.pt"
vae_ckpt_path = "/content/PartPacker/pretrained/vae.pt"

TRIMESH_GLB_EXPORT = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]]).astype(np.float32)
MAX_SEED = np.iinfo(np.int32).max
bg_remover = rembg.new_session()

# model config
model_config = ModelConfig(
    vae_conf="vae.configs.part_woenc",
    vae_ckpt_path=vae_ckpt_path,
    qknorm=True,
    qknorm_type="RMSNorm",
    use_pos_embed=False,
    dino_model="dinov2_vitg14",
    hidden_dim=1536,
    flow_shift=3.0,
    logitnorm_mean=1.0,
    logitnorm_std=1.0,
    latent_size=4096,
    use_parts=True,
)

gpu_config = {'num_gpus': 1 if torch.cuda.is_available() else 0}
model = Model(model_config).eval().cuda().bfloat16()
multi_gpu_enabled = False

# load weight
ckpt_dict = torch.load(flow_ckpt_path, weights_only=True)
if multi_gpu_enabled:
    model.base_model.load_state_dict(ckpt_dict, strict=True)
else:
    model.load_state_dict(ckpt_dict, strict=True)

# get random seed
def get_random_seed(randomize_seed, seed):
    if randomize_seed:
        seed = np.random.randint(0, MAX_SEED)
    return seed

"""### Image Segmentation Function"""

# Similar function as 'process_image' from app.py
# Also added code to write the segmented image to a path
def image_segmentation(image_path, output_dir="output"):
    image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    if image.shape[-1] == 4:
        image = cv2.cvtColor(image, cv2.COLOR_BGRA2RGBA)
    else:
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        # bg removal if there is no alpha channel
        image = rembg.remove(image, session=bg_remover)    # [H, W, 4]
    mask = image[..., -1] > 0
    image = recenter_foreground(image, mask, border_ratio=0.1)
    image = cv2.resize(image, (518, 518), interpolation=cv2.INTER_AREA)
    print(image.shape)
    # Write and return segment image path
    output_dir = os.path.join(output_dir, "seg")
    os.makedirs(output_dir, exist_ok=True)
    seg_image_path = os.path.join(output_dir, os.path.basename(image_path))
    cv2.imwrite(seg_image_path, image)
    return seg_image_path

"""### Generate 3D Geometry Function"""

# Similar function to 'process_3d' from app.py
# Changed output paths
def generate_3d_geometry(
    input_path,
    output_dir="output",
    num_steps=50,
    cfg_scale=7,
    grid_res=384,
    seed=42,
    simplify_mesh=False,
    target_num_faces=100000
):
    # Read from image path
    input_image = cv2.imread(input_path, cv2.IMREAD_UNCHANGED)

    # seed
    kiui.seed_everything(seed)

    # Display GPU memory usage for multi-GPU mode
    if multi_gpu_enabled and gpu_config['num_gpus'] > 0:
        for i in range(gpu_config['num_gpus']):
            memory_allocated = torch.cuda.memory_allocated(i) / 1024**3
            memory_reserved = torch.cuda.memory_reserved(i) / 1024**3
            print(f"GPU {i}: Allocated Memory {memory_allocated:.2f}GB, Reserved {memory_reserved:.2f}GB")

    # output path
    # os.makedirs("output", exist_ok=True)
    # output_glb_path = f"output/partpacker_{datetime.now().strftime('%Y%m%d_%H%M%S')}.glb"
    if output_dir[-1] == "/": output_dir = output_dir[:-1]
    output_dir = os.path.join(output_dir, "generate")
    os.makedirs(output_dir, exist_ok=True)
    image_stem = os.path.basename(input_path).split(".")[0]
    output_glb_path = os.path.join(output_dir, f"{image_stem}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.glb")

    # input image (assume processed to RGBA uint8)
    image = input_image.astype(np.float32) / 255.0
    image = image[..., :3] * image[..., 3:4] + (1 - image[..., 3:4])    # white background
    image_tensor = torch.from_numpy(image).permute(2, 0, 1).contiguous().unsqueeze(0).float()

    if not multi_gpu_enabled:
        image_tensor = image_tensor.cuda()

    data = {"cond_images": image_tensor}

    if multi_gpu_enabled:
        # Multi-GPU processing
        results = model(data, num_steps=num_steps, cfg_scale=cfg_scale)
        latent = results["latent"]

        # Query mesh - process each part separately to save memory
        data_part0 = {"latent": latent[:, : model.config.latent_size, :]}
        data_part1 = {"latent": latent[:, model.config.latent_size :, :]}

        # Generate mesh for part 0
        results_part0 = model.vae_decode(data_part0, resolution=grid_res)

        # Clear memory
        if gpu_config['num_gpus'] > 0:
            torch.cuda.empty_cache()

        # Generate mesh for part 1
        results_part1 = model.vae_decode(data_part1, resolution=grid_res)

        # Clear memory
        if gpu_config['num_gpus'] > 0:
            torch.cuda.empty_cache()
    else:
        # Single GPU processing (original code)
        with torch.inference_mode():
            results = model(data, num_steps=num_steps, cfg_scale=cfg_scale)

        latent = results["latent"]

        # query mesh
        data_part0 = {"latent": latent[:, : model.config.latent_size, :]}
        data_part1 = {"latent": latent[:, model.config.latent_size :, :]}

        with torch.inference_mode():
            results_part0 = model.vae(data_part0, resolution=grid_res)
            results_part1 = model.vae(data_part1, resolution=grid_res)

    if not simplify_mesh:
        target_num_faces = -1

    vertices, faces = results_part0["meshes"][0]
    mesh_part0 = trimesh.Trimesh(vertices, faces)
    mesh_part0.vertices = mesh_part0.vertices @ TRIMESH_GLB_EXPORT.T
    mesh_part0 = postprocess_mesh(mesh_part0, target_num_faces)
    parts = mesh_part0.split(only_watertight=False)

    vertices, faces = results_part1["meshes"][0]
    mesh_part1 = trimesh.Trimesh(vertices, faces)
    mesh_part1.vertices = mesh_part1.vertices @ TRIMESH_GLB_EXPORT.T
    mesh_part1 = postprocess_mesh(mesh_part1, target_num_faces)
    parts.extend(mesh_part1.split(only_watertight=False))

    # some parts only have 1 face, seems a problem of trimesh.split.
    parts = [part for part in parts if len(part.faces) > 10]

    # split connected components and assign different colors
    for j, part in enumerate(parts):
        # each component uses a random color
        part.visual.vertex_colors = get_random_color(j, use_float=True)

    mesh = trimesh.Scene(parts)
    # export the whole mesh
    mesh.export(output_glb_path)

    return output_glb_path

"""### Segment and Generate Function"""

def segment_and_generate_images(
    input_path,
    limit=1,
    output_dir='/content/output/',
    num_steps=50,
    cfg_scale=7,
    grid_res=384,
    seed=42,
    simplify_mesh=False,
    target_num_faces=100000
):
    if os.path.isdir(input_path):
        paths = glob.glob(os.path.join(input_path, "*"))
        paths = sorted(paths)
        if limit > 0:
            paths = paths[: limit]
    else:
        paths = [input_path]

    mesh_list = []
    for image_path in paths:
        seg_image_path = image_segmentation(image_path, output_dir)
        print(cv2.imread(seg_image_path, cv2.IMREAD_UNCHANGED).shape)
        glb_path = generate_3d_geometry(
            seg_image_path,
            output_dir,
            num_steps,
            cfg_scale,
            grid_res,
            seed,
            simplify_mesh,
            target_num_faces
        )
        mesh_list.append([
            seg_image_path,
            glb_path
        ])
    return mesh_list

"""## Test with good_001 weld"""

media = "/content/datara_transfer/backend/dataset/train/images/good/good_001.jpg"
label = "good"
image = cv2.imread(media, cv2.IMREAD_UNCHANGED)

import os

media_stem = os.path.basename(media).split(".")[0]
os.makedirs(f'/content/output/{media_stem}/masks', exist_ok=True)

"""### VLM

#### Condition
"""

output = generate_text(
    model,
    processor,
    media,
    label,
    "condition"
)
for o in output:
    print(o)

"""#### Operation Type"""

output = generate_text(
    model,
    processor,
    media,
    label,
    "operation type"
)
for o in output:
    print(o)

"""#### Sensor Modalities"""

output = generate_text(
    model,
    processor,
    media,
    label,
    "sensor modalities"
)
for o in output:
    print(o)

"""### Mask"""

masks = mask_generator.generate(image)

print(len(masks))
print(masks[0].keys())

# plt.figure(figsize=(20, 20))
plt.imshow(image)
show_anns(masks)
plt.axis('off')
plt.show()

# Empty directory
!rm -rf /content/output/{media_stem}/masks/*

for i, mask in enumerate(masks):
    masked_image = image * mask['segmentation'][:, :, None]
    b,g,r = cv2.split(masked_image)

    # plt.imshow(cv2.merge((b, g, r, 255*np.ones(b.shape, dtype=b.dtype))))
    # plt.axis('off')
    # plt.show()

    cv2.imwrite(f'/content/output/{media_stem}/masks/mask_{i}.png', masked_image)

for i, mask in enumerate(masks):
    masked_image = image * mask['segmentation'][:, :, None]
    b,g,r = cv2.split(masked_image)

    plt.imshow(cv2.merge((b, g, r, 255*np.ones(b.shape, dtype=b.dtype))))
    plt.axis('off')
    plt.show()

"""### 3D Reconstruction"""

glb_path = generate_3d_geometry(
    '/content/output/masks/good_001.png',
    output_dir='/content/output/',
    num_steps=50,
    cfg_scale=7.0,
    grid_res=384,
    seed=42,
    simplify_mesh=False,
    target_num_faces=100000
)

# mesh_list = segment_and_generate_images(
#     "/content/output/masks/good_001.png",
#     limit=1,
#     output_dir='/content/output/',
#     num_steps=50,
#     cfg_scale=7.0,
#     grid_res=384,
#     target_num_faces=100000
# )

"""### Bipartite Contraction Command -> Dual Volume Packer"""

!ls /content/output/generate

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PartPacker

!python data/bipartite_contraction.py /content/output/generate/good_001_20251031_201604.glb \
    --workspace /content/output/dvp/

!ls /content/output/dvp

trimesh.load('/content/output/generate/good_001_20251031_201604.glb').show()

trimesh.load('/content/output/dvp/good_001_20251031_201604.obj').show()

trimesh.load('/content/output/dvp/good_001_20251031_201604_color0.obj').show()

trimesh.load('/content/output/dvp/good_001_20251031_201604_color1.obj').show()

"""## Test with BMW Manufacturing Video"""

# https://www.youtube.com/watch?v=kh9QXalRERw
# 10:43 - 10:58
# 11:00 - 11:10
# 27:16

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/IDEA-Research/Grounded-SAM-2.git

# %cd Grounded-SAM-2/checkpoints
!bash download_ckpts.sh

# %cd ../gdino_checkpoints
!bash download_ckpts.sh

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

from google.colab import drive
drive.mount('/content/gdrive')

media = "/content/gdrive/MyDrive/Colab Notebooks/MVP/BMW Front.mp4"
video = cv2.VideoCapture(media)

from IPython.display import HTML
from base64 import b64encode

mp4 = open(media,'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""
<video width=400 controls>
      <source src="%s" type="video/mp4">
</video>
""" % data_url)

media_stem = os.path.basename(media).split(".")[0]
os.makedirs(f'/content/output/{media_stem}/masks', exist_ok=True)

"""### VLM

#### Condition
"""

output = generate_text(
    model,
    processor,
    media,
    label,
    "condition"
)
for o in output:
    print(o)

"""#### Operation Type"""

output = generate_text(
    model,
    processor,
    media,
    label,
    "operation type"
)
for o in output:
    print(o)

"""#### Sensor Modalities"""

output = generate_text(
    model,
    processor,
    media,
    label,
    "sensor modalities"
)
for o in output:
    print(o)

"""### SAM2 Mask"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/sam2

!pip install supervision

sam2_model = build_sam2_video_predictor(model_cfg, sam2_checkpoint, device=device)

import supervision as sv

frames_generator = sv.get_video_frames_generator(media)
sink = sv.ImageSink(
    target_dir_path="/content/video/",
    image_name_pattern="{:05d}.jpeg")

with sink:
    for frame in frames_generator:
        sink.save_image(frame)

inference_state = sam2_model.init_state("/content/video/")

points = np.array([[703, 303]], dtype=np.float32)
labels = np.array([1])
frame_idx = 0
tracker_id = 1

_, object_ids, mask_logits = sam2_model.add_new_points(
    inference_state=inference_state,
    frame_idx=frame_idx,
    obj_id=tracker_id,
    points=points,
    labels=labels,
)

mask_logits[0][0].shape

plt.imshow(cv2.imread('/content/video/00000.jpeg', cv2.COLOR_RGB2BGR))
plt.axis('off')
plt.show()

video_img = cv2.imread('/content/video/00000.jpeg', cv2.IMREAD_UNCHANGED)

video_img.shape

(torch.tensor([[1.0, 2.0], [3.0, 4.0]]))

mask_logits.cpu().numpy()

masked_image = video_img * (mask_logits.cpu().numpy())[0][0][:, :, None]
b,g,r = cv2.split(masked_image)

plt.imshow(cv2.merge((b, g, r, 255*np.ones(b.shape, dtype=b.dtype))))
plt.axis('off')
plt.show()

import os
import cv2
import torch
import numpy as np
import supervision as sv

from pathlib import Path
from tqdm import tqdm
from PIL import Image
from sam2.build_sam import build_sam2_video_predictor, build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
from utils.track_utils import sample_points_from_masks
from utils.video_utils import create_video_from_images

"""
Hyperparam for Ground and Tracking
"""
MODEL_ID = "IDEA-Research/grounding-dino-tiny"
VIDEO_PATH = media
TEXT_PROMPT = ""
OUTPUT_VIDEO_PATH = media + "_output.mp4"
SOURCE_VIDEO_FRAME_DIR = "./custom_video_frames"
SAVE_TRACKING_RESULTS_DIR = "./tracking_results"
PROMPT_TYPE_FOR_VIDEO = "mask" # choose from ["point", "box", "mask"]

"""
Step 1: Environment settings and model initialization for SAM 2
"""
# use bfloat16 for the entire notebook
torch.autocast(device_type="cuda", dtype=torch.bfloat16).__enter__()

if torch.cuda.get_device_properties(0).major >= 8:
    # turn on tfloat32 for Ampere GPUs (https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices)
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True

# init sam image predictor and video predictor model
# sam2_checkpoint = "./checkpoints/sam2.1_hiera_large.pt"
# model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml"

video_predictor = build_sam2_video_predictor(model_cfg, sam2_checkpoint)
sam2_image_model = build_sam2(model_cfg, sam2_checkpoint)
image_predictor = SAM2ImagePredictor(sam2_image_model)

# build grounding dino from huggingface
model_id = MODEL_ID
device = "cuda" if torch.cuda.is_available() else "cpu"
processor = AutoProcessor.from_pretrained(model_id)
grounding_model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id).to(device)


"""
Custom video input directly using video files
"""
video_info = sv.VideoInfo.from_video_path(VIDEO_PATH)  # get video info
print(video_info)
frame_generator = sv.get_video_frames_generator(VIDEO_PATH, stride=1, start=0, end=None)

# saving video to frames
source_frames = Path(SOURCE_VIDEO_FRAME_DIR)
source_frames.mkdir(parents=True, exist_ok=True)

with sv.ImageSink(
    target_dir_path=source_frames,
    overwrite=True,
    image_name_pattern="{:05d}.jpg"
) as sink:
    for frame in tqdm(frame_generator, desc="Saving Video Frames"):
        sink.save_image(frame)

# scan all the JPEG frame names in this directory
frame_names = [
    p for p in os.listdir(SOURCE_VIDEO_FRAME_DIR)
    if os.path.splitext(p)[-1] in [".jpg", ".jpeg", ".JPG", ".JPEG"]
]
frame_names.sort(key=lambda p: int(os.path.splitext(p)[0]))

# init video predictor state
inference_state = video_predictor.init_state(video_path=SOURCE_VIDEO_FRAME_DIR)

ann_frame_idx = 0  # the frame index we interact with
"""
Step 2: Prompt Grounding DINO 1.5 with Cloud API for box coordinates
"""

# prompt grounding dino to get the box coordinates on specific frame
img_path = os.path.join(SOURCE_VIDEO_FRAME_DIR, frame_names[ann_frame_idx])
image = Image.open(img_path)
inputs = processor(images=image, text=TEXT_PROMPT, return_tensors="pt").to(device)
with torch.no_grad():
    outputs = grounding_model(**inputs)

results = processor.post_process_grounded_object_detection(
    outputs,
    inputs.input_ids,
    threshold=0.4,
    text_threshold=0.3,
    target_sizes=[image.size[::-1]]
)

input_boxes = results[0]["boxes"].cpu().numpy()
confidences = results[0]["scores"].cpu().numpy().tolist()
class_names = results[0]["labels"]

print(input_boxes)

# prompt SAM image predictor to get the mask for the object
image_predictor.set_image(np.array(image.convert("RGB")))

# process the detection results
OBJECTS = class_names

print(OBJECTS)

# prompt SAM 2 image predictor to get the mask for the object
masks, scores, logits = image_predictor.predict(
    point_coords=None,
    point_labels=None,
    box=input_boxes,
    multimask_output=False,
)
# convert the mask shape to (n, H, W)
if masks.ndim == 4:
    masks = masks.squeeze(1)

"""
Step 3: Register each object's positive points to video predictor with seperate add_new_points call
"""

assert PROMPT_TYPE_FOR_VIDEO in ["point", "box", "mask"], "SAM 2 video predictor only support point/box/mask prompt"

# If you are using point prompts, we uniformly sample positive points based on the mask
if PROMPT_TYPE_FOR_VIDEO == "point":
    # sample the positive points from mask for each objects
    all_sample_points = sample_points_from_masks(masks=masks, num_points=10)

    for object_id, (label, points) in enumerate(zip(OBJECTS, all_sample_points), start=1):
        labels = np.ones((points.shape[0]), dtype=np.int32)
        _, out_obj_ids, out_mask_logits = video_predictor.add_new_points_or_box(
            inference_state=inference_state,
            frame_idx=ann_frame_idx,
            obj_id=object_id,
            points=points,
            labels=labels,
        )
# Using box prompt
elif PROMPT_TYPE_FOR_VIDEO == "box":
    for object_id, (label, box) in enumerate(zip(OBJECTS, input_boxes), start=1):
        _, out_obj_ids, out_mask_logits = video_predictor.add_new_points_or_box(
            inference_state=inference_state,
            frame_idx=ann_frame_idx,
            obj_id=object_id,
            box=box,
        )
# Using mask prompt is a more straightforward way
elif PROMPT_TYPE_FOR_VIDEO == "mask":
    for object_id, (label, mask) in enumerate(zip(OBJECTS, masks), start=1):
        labels = np.ones((1), dtype=np.int32)
        _, out_obj_ids, out_mask_logits = video_predictor.add_new_mask(
            inference_state=inference_state,
            frame_idx=ann_frame_idx,
            obj_id=object_id,
            mask=mask
        )
else:
    raise NotImplementedError("SAM 2 video predictor only support point/box/mask prompts")


"""
Step 4: Propagate the video predictor to get the segmentation results for each frame
"""
video_segments = {}  # video_segments contains the per-frame segmentation results
for out_frame_idx, out_obj_ids, out_mask_logits in video_predictor.propagate_in_video(inference_state):
    video_segments[out_frame_idx] = {
        out_obj_id: (out_mask_logits[i] > 0.0).cpu().numpy()
        for i, out_obj_id in enumerate(out_obj_ids)
    }

"""
Step 5: Visualize the segment results across the video and save them
"""

if not os.path.exists(SAVE_TRACKING_RESULTS_DIR):
    os.makedirs(SAVE_TRACKING_RESULTS_DIR)

ID_TO_OBJECTS = {i: obj for i, obj in enumerate(OBJECTS, start=1)}

for frame_idx, segments in video_segments.items():
    img = cv2.imread(os.path.join(SOURCE_VIDEO_FRAME_DIR, frame_names[frame_idx]))

    object_ids = list(segments.keys())
    masks = list(segments.values())
    masks = np.concatenate(masks, axis=0)

    detections = sv.Detections(
        xyxy=sv.mask_to_xyxy(masks),  # (n, 4)
        mask=masks, # (n, h, w)
        class_id=np.array(object_ids, dtype=np.int32),
    )
    box_annotator = sv.BoxAnnotator()
    annotated_frame = box_annotator.annotate(scene=img.copy(), detections=detections)
    label_annotator = sv.LabelAnnotator()
    annotated_frame = label_annotator.annotate(annotated_frame, detections=detections, labels=[ID_TO_OBJECTS[i] for i in object_ids])
    mask_annotator = sv.MaskAnnotator()
    annotated_frame = mask_annotator.annotate(scene=annotated_frame, detections=detections)
    cv2.imwrite(os.path.join(SAVE_TRACKING_RESULTS_DIR, f"annotated_frame_{frame_idx:05d}.jpg"), annotated_frame)


"""
Step 6: Convert the annotated frames to video
"""

create_video_from_images(SAVE_TRACKING_RESULTS_DIR, OUTPUT_VIDEO_PATH)